stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    - data_ingestion.random_state
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data_preprocessing.py
    outs:
    - data/interim

  feature_extraction:
    cmd: python src/feature_extraction.py
    deps:
    - data/interim/train_processed.csv
    - src/feature_extraction.py
    outs:
    - data/processed
    - models/tfidf_vectorizer.joblib

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    params:
    - model_building.random_state 
    - model_building.n_estimators
    - model_building.max_depth
    - model_building.learning_rate
    - model_building.num_leaves
    - model_building.min_child_samples
    - model_building.subsample
    - model_building.colsample_bytree
    - model_building.reg_alpha
    - model_building.reg_lambda
    - model_building.objective
    - model_building.num_class
    - model_building.class_weight
    outs:
    - models/lgbm_model.joblib

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/lgbm_model.joblib
    - models/tfidf_vectorizer.joblib
    - data/interim/test_processed.csv
    - src/model_evaluation.py
    outs:
    - data/visualizations/confusion_matrix_Test_Data.png
    - experiment_info.json

  model_registration:
    cmd: python src/register_model.py
    deps:
    - src/register_model.py
    - experiment_info.json