stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.validation_size
    - data_ingestion.test_size
    - data_ingestion.random_state
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/validation.csv
    - data/raw/test.csv
    - src/data_preprocessing.py
    outs:
    - data/interim

  feature_extraction:
    cmd: python src/feature_extraction.py
    deps:
    - data/interim/train_processed.csv
    - src/feature_extraction.py
    outs:
    - data/processed
