stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.validation_size
    - data_ingestion.test_size
    - data_ingestion.random_state
    outs:
    - data/raw